apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pixel-board.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.api.jwtSecret | b64enc | quote }}
  MONGO_URI: {{ include "pixel-board.mongoUri" . | b64enc | quote }}
