apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: {{ .Values.namespace }}
  labels:
    app: api
    {{- include "pixel-board.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.api.staticIp }}
  selector:
    app: api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
